// import React, { useEffect, useState } from 'react';
// import { GetServerSideProps } from 'next';
// import type { NextPage } from 'next';

// import * as pdfMake from 'pdfmake/build/pdfmake';
// import * as pdfFonts from 'pdfmake/build/vfs_fonts';
// import dayjs from 'dayjs';

// interface prescription {
// 	name: string;
// 	address: string;
// 	id: string;
// 	pDetails: [];
// }

// const Prescription: NextPage = ({ data }) => {
// 	const [prescription, setPrescription] = useState<prescription>({});
// 	const [pDetails, setPDetails] = useState([]);

// 	useEffect(() => {
// 		setPrescription(JSON.parse(localStorage.getItem(pid)));
// 		setPDetails(prescription.pDetails);
// 		generateBill();
// 	}, []);

// 	const prescriptionCreatedAt = dayjs().format('DD-MM-YYYY hh:mm A');

// 	pdfMake.vfs = pdfFonts.pdfMake.vfs;

// 	const generateBill = () => {
// 		pdfMake.createPdf(dd).download('pres' + prescription.name + '_' + pid);
// 	};

// 	var dd = {
// 		info: {
// 			title: prescription.name + '_' + pid,
// 			author: 'Dr. Raymond Holt',
// 		},

// 		content: [
// 			{
// 				text: 'Sample Hospital',
// 				style: 'header',
// 				margin: [5, 2, 10, 20],
// 			},
// 			{
// 				text: 'Dr. Raymond Holt',
// 				style: 'subheader',
// 				margin: [5, 2, 10, 20],
// 			},
// 			{
// 				text: 'Patient Name: ' + prescription.name,
// 				style: 'text',
// 				margin: [5, 2, 10, 20],
// 			},
// 			{
// 				text: 'Patient Address: ' + prescription.address,
// 				style: 'text',
// 			},
// 			{
// 				text: 'Issued at' + prescriptionCreatedAt,
// 				style: 'text',
// 			},
// 			// {
// 			// 	layout: 'lightHorizontalLines', // optional
// 			// 	table: {
// 			// 		// headers are automatically repeated if the table spans over multiple pages
// 			// 		// you can declare how many rows should be treated as headers
// 			// 		headerRows: 1,
// 			// 		widths: ['*', '*', '*', '*', '*'],
// 			// 		body: prescription.pDetails.map(item => item),
// 			// 		margin: [5, 10, 10, 20],
// 			// 	},
// 			// },
// 			{
// 				text: 'Prescription Verified using ID: ' + pid,
// 				style: 'header',
// 				margin: [5, 40, 10, 20],
// 			},

// 			'DoctorID: aZ23Xyu2qwepo',
// 			'Mail: raymondholt@sample.com',
// 			'PrescriptionID for verification,reference,keepsafe' + pid,

// 			{
// 				text: 'Generated by Sano .For any queries , please reach out to mail@sano.co',
// 				style: 'boldText',
// 				margin: [5, 40, 10, 20],
// 			},
// 		],
// 		styles: {
// 			header: {
// 				fontSize: 18,
// 				bold: true,
// 			},
// 			subheader: {
// 				fontSize: 12,
// 				bold: true,
// 			},
// 			text: {
// 				fontSize: 8,
// 			},
// 			boldText: {
// 				bold: true,
// 			},
// 		},
// 	};

// 	return (
// 		<div className='flex flex-row items-center justify-center w-screen h-screen bg-blue-100'>
// 			<div className='flex flex-row items-center justify-center bg-white rounded-lg w-168 h-44'>
// 				<div className='flex flex-col items-center justify-center space-y-2'>
// 					<h4 className='text-sm font-semibold text-gray-800'>
// 						Prescription generated for {prescription.name}
// 					</h4>
// 					<p className='text-xs font-light text-gray-400'>{prescription.id}</p>
// 				</div>
// 			</div>
// 		</div>
// 	);
// };

// export const getServerSideProps: GetServerSideProps = async context => {
// 	const { url } = context.params;
// 	const data = JSON.parse(url);
// 	return {
// 		props: { data }, // will be passed to the page component as props
// 	};
// };

// export default Prescription;

import React from 'react';

function hello() {
	return <div></div>;
}

export default hello;
